package com.MultipleTableFetch.Entity;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Employee implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "AutoGenerated")
    private int id;
    private String name;
    private int salary;
    @JsonManagedReference
    @OneToOne(cascade = CascadeType.ALL, mappedBy = "employee")
    private Gender gender;
    @JsonManagedReference
    @OneToOne(cascade = CascadeType.ALL, mappedBy = "employee")
    private Department department;

}